name: 部署 Hexo 文档

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: 设置 Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          # 删掉 cache: pnpm ！解决冲突
          # cache: pnpm

      - name: 安装依赖
        run: |
          pnpm ci

      - name: 清理并生成静态文件
        run: |
          npx hexo clean
          npx hexo generate   # 生成到 public 目录

      - name: 部署文档部署到 gh-pages 分支
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: src/.vuepress/dist
